# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/seagate/Development/FPGA/MB_LED/MB_LED.cache/wt [current_project]
set_property parent.project_path /mnt/seagate/Development/FPGA/MB_LED/MB_LED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /mnt/seagate/Development/FPGA/IP_Repository
  /mnt/seagate/Development/FPGA/ip_repo
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0.xci
set_property is_locked true [get_files /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0.xci]

synth_design -top lite_slv_LFSR_0 -part xc7a100tcsg324-1 -mode out_of_context
rename_ref -prefix_all lite_slv_LFSR_0_
write_checkpoint -noxdef lite_slv_LFSR_0.dcp
catch { report_utilization -file lite_slv_LFSR_0_utilization_synth.rpt -pb lite_slv_LFSR_0_utilization_synth.pb }
if { [catch {
  file copy -force /mnt/seagate/Development/FPGA/MB_LED/MB_LED.runs/lite_slv_LFSR_0_synth_1/lite_slv_LFSR_0.dcp /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /mnt/seagate/Development/FPGA/MB_LED/MB_LED.ip_user_files/ip/lite_slv_LFSR_0]} {
  catch { 
    file copy -force /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0_stub.v /mnt/seagate/Development/FPGA/MB_LED/MB_LED.ip_user_files/ip/lite_slv_LFSR_0
  }
}

if {[file isdir /mnt/seagate/Development/FPGA/MB_LED/MB_LED.ip_user_files/ip/lite_slv_LFSR_0]} {
  catch { 
    file copy -force /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/ip/lite_slv_LFSR_0/lite_slv_LFSR_0_stub.vhdl /mnt/seagate/Development/FPGA/MB_LED/MB_LED.ip_user_files/ip/lite_slv_LFSR_0
  }
}
