# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/seagate/Development/FPGA/MB_LED/MB_LED.cache/wt [current_project]
set_property parent.project_path /mnt/seagate/Development/FPGA/MB_LED/MB_LED.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /mnt/seagate/Development/FPGA/IP_Repository [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/design_gpio_led.bd
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_microblaze_0_0/design_gpio_led_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_microblaze_0_0/design_gpio_led_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_microblaze_0_0/design_gpio_led_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_dlmb_v10_0/design_gpio_led_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_dlmb_v10_0/design_gpio_led_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_ilmb_v10_0/design_gpio_led_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_ilmb_v10_0/design_gpio_led_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_dlmb_bram_if_cntlr_0/design_gpio_led_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_ilmb_bram_if_cntlr_0/design_gpio_led_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_lmb_bram_0/design_gpio_led_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_mdm_1_0/design_gpio_led_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_mdm_1_0/design_gpio_led_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_mdm_1_0/design_gpio_led_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_clk_wiz_1_0/design_gpio_led_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_clk_wiz_1_0/design_gpio_led_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_clk_wiz_1_0/design_gpio_led_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_rst_clk_wiz_1_100M_0/design_gpio_led_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_rst_clk_wiz_1_100M_0/design_gpio_led_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_rst_clk_wiz_1_100M_0/design_gpio_led_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_xbar_0/design_gpio_led_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/design_gpio_led_ooc.xdc]
set_property is_locked true [get_files /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/design_gpio_led.bd]

read_vhdl -library xil_defaultlib /mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/sources_1/bd/design_gpio_led/hdl/design_gpio_led_wrapper.vhd
read_xdc {{/mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/constrs_1/imports/Nexys 4 DDR/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{/mnt/seagate/Development/FPGA/MB_LED/MB_LED.srcs/constrs_1/imports/Nexys 4 DDR/Nexys4DDR_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_gpio_led_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef design_gpio_led_wrapper.dcp
catch { report_utilization -file design_gpio_led_wrapper_utilization_synth.rpt -pb design_gpio_led_wrapper_utilization_synth.pb }
